print("\nMenu do Gerenciador de tarefas:")
print("1. Adicionar tarefa")
print("2. Ver tarefas")
print("3. Atualizar tarefa")
print("4 Completar tarefa")
print("5. Deletar tarefa completas")
print("6. Sair")